In [1]:
import pandas as pd

a. Create a series containing a dictionary that includes product names and product IDs.

In [3]:
products = {
    "Laptop": 101,
    "Mouse": 102,
    "Keyboard": 103,
    "Monitor": 104,
    "Headset": 105
}

product_series = pd.Series(products)

print(product_series)

Laptop      101
Mouse       102
Keyboard    103
Monitor     104
Headset     105
dtype: int64

b. Create a dataframe containing a dictionary with 4 columns, and each column contains 5 
data points. There should be no similarities between students.

In [4]:
students = {
    "Name": ["muhammad", "iqbal", "fadel", "najwa", "aurellia"],
    "Age": [20, 21, 18, 19, 20],
    "Gender": ["male", "male", "male", "female", "female"],
    "GPA": [3.5, 3.6, 3.7, 3.8, 3.9]
    }

df_students = pd.DataFrame(students)

df_students

       Name  Age  Gender  GPA
0  muhammad   20    male  3.5
1     iqbal   21    male  3.6
2     fadel   18    male  3.7
3     najwa   19  female  3.8
4  aurellia   20  female  3.9

c. Add 1 new column.

In [5]:
df_students["Status"] = ["Active", "Active", "Inactive", "Active", "Inactive"]

df_students

       Name  Age  Gender  GPA    Status
0  muhammad   20    male  3.5    Active
1     iqbal   21    male  3.6    Active
2     fadel   18    male  3.7  Inactive
3     najwa   19  female  3.8    Active
4  aurellia   20  female  3.9  Inactive

d. Sort the dataframe, for example, alphabetically if the column is 'Name'.

In [ ]:
df_sorted = df_students.sort_values(by="Name")

df_sorted

       Name  Age  Gender  GPA    Status
4  aurellia   20  female  3.9  Inactive
2     fadel   18    male  3.7  Inactive
1     iqbal   21    male  3.6    Active
0  muhammad   20    male  3.5    Active
3     najwa   19  female  3.8    Active